### ISSUE TITLE
How do I make Code Blocks work with MDX JS Loader?

### ISSUE THREAD

**Issue by deadcoder0904** [peduarte/ped.ro#32]
Hey @peduarte, we talked recently on Twitter. I am facing some issues. Let me know if you've ever worked with MDX JS Loader & know how to solve these issues.

So I am trying to follow https://ped.ro/blog/code-blocks-but-better

My own blog is a clone of https://github.com/tailwindlabs/blog.tailwindcss.com/

I am having a hard time converting the styles part from MDX Bundler into MDX JS Loader especially after the heading **Part 2 - UI** where you use Stitches & I want to use Tailwind.

Where do I put those styles so I can have different colored themes? I am specifically not understanding how to parse `theme=purple`?

I am using [tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography) like https://github.com/tailwindlabs/blog.tailwindcss.com/blob/master/tailwind.config.js#L52-L89

So where do I have to interpret that `theme=purple` part?

Also, it's not clear how to use **Prism Themes**. I did download a Prism Dracula CSS file but my code block is unstyled now.

Another part under **Part 3 - Component substitution**, you are using XDMs Component Substitution. Where do I put the `Pre`, `RegisterLink` & `H` component when I am using `@mdx-js/loader` like https://github.com/tailwindlabs/blog.tailwindcss.com/blob/master/next.config.js#L44?

Again, thank you for an amazing blog. Would love to use it on my own blog if you do know the answers :)

**Comment by peduarte** [comment]
@deadcoder0904 hi! thanks for that 😄 

> Where do I put those styles so I can have different colored themes?

Im not sure how you'd approach this with Tailwind. it's a different approach and doesn't support the concept of variants that Stitches does.

But the best way to think of it, is that based on the theme you'd want to apply different class names.

Regarding the dracula theme, you need to make sure you include the theme in your page, something like:
```js
import './dracula-theme.css'
```

Regarding component substitution, you need the `MDXProvider`, like this: https://github.com/tailwindlabs/blog.tailwindcss.com/blob/9da36a0e0aff8ff8bc4160d7f20dd7097ffc9147/src/components/Post.js#L109


Sorry I cant help you much, the article isn't a tutorial its just sharing my approach. 

Thanks!

**Comment by deadcoder0904** [comment]
No problem. It's confusing with Tailwind. I did get the `rehype` part to work, just the styles aren't applied & don't know how to use different themes with Tailwind.

Yep, I was trying `MDXProvider` but it was commented out so didn't work. Will try again :)

**Comment by peduarte** [comment]
@deadcoder0904 if you have a repo, send me the link and I'll take a look if I have time

**Comment by deadcoder0904** [comment]
Sure, will do it in some time. I'll see if it works out first :)

**Comment by deadcoder0904** [comment]
Hey @peduarte so I uploaded it → https://github.com/deadcoder0904/better-code-blocks

Check the README for more info.

I can also access `theme` variable passed through the code block in MDX on `Pre` (see console) → https://github.com/deadcoder0904/better-code-blocks/blob/main/src/components/mdx/Pre.tsx#L4

But don't know how to style change it a/c to the theme. Probably have to use this video as an inspiration → https://www.youtube.com/watch?v=MAtaT8BZEAo

I'll try component substitution of others in the meantime :)

**Comment by deadcoder0904** [comment]
Hey @peduarte I think Tailwind Themes can be implemented using CSS variables. I'm giving that a shot → https://github.com/deadcoder0904/better-code-blocks/commit/edc0465b4f85c1720382f86692849e508414728a

Additionally, I'd like to ask if `$4` is a bug in the blog post as you don't have `$4` for spaces. You only have upto `$3` so do let me know about that:

```css
'.token.deleted:not(.prefix), .token.inserted:not(.prefix)': {
    display: 'block',
    px: '$4',
    mx: '-$4',
  },
```

**Comment by peduarte** [comment]
@deadcoder0904 yeah, I left some tokens out for brevity, but I'll update it to remove confusion.

**Comment by deadcoder0904** [comment]
I have reached pretty far (99%) with styles working.

### Here are a few suggestions:

1. `$$lineNumbers` isn't set anywhere else. Maybe a variable missing?
2. Under Component Substitution, `rangeParser` hasn't been imported on top so I was confused

### And here's my doubt:

I haven't added `Preview` & collapsible thing on `code` but kept it simply `code`. `code` gets access to `theme` properly but `pre` doesn't. `pre` gets access to `theme` by going through `children.props?.theme` which is weird.

I have used `MDXComponents` properly. I don't think XDM does some magic underhood so that I have to change underlying `rehype` plugins but the data I get is weird.

Can you check this to confirm? I think we're 99% there.

`H` doesn't work. `RegisterLink` works properly.

I would like to know how I should implement highlights as I can see it sets `highlighted=true` in DOM? So maybe I can use turn it into a class & style it.

I have made use of CSS variables & different classes to implement themes rather than going the Tailwind way. I'll probably switch to Tailwind config (like Stitches) once I get this working.

The repo → https://github.com/deadcoder0904/better-code-blocks

Here's are the last 2 commits to check → https://github.com/deadcoder0904/better-code-blocks/commit/45d7e6a936d82d12d3abc292cd5eeb177ec4ddde & https://github.com/deadcoder0904/better-code-blocks/commit/9c21c0ce48206fddb6c8d7d013733fe10b1cef31

The files you need to check are `pages/styles/custom-prism.css`, `src/components/mdx/Pre.tsx`, `src/components/mdx/Code.tsx`, & `src/components/mdx/H.tsx`
