### ISSUE TITLE
images overflowing

### ISSUE THREAD

**Issue by Deep-Codes** [peduarte/ped.ro#39]
Hey Pedro!

I think images in this [Blog](https://ped.ro/blog/wallop-system-built-with-modulz) are missing width.

<img width="1006" alt="Screenshot 2021-07-19 at 12 24 42 AM" src="https://user-images.githubusercontent.com/61158210/126079010-8d78b20e-55b8-47a8-a0c6-77a541309555.png">

**Comment by peduarte** [comment]
Thanks for that, will take a look!

**Comment by peduarte** [comment]
Fixed
